# Generated by Django 2.1.2 on 2018-10-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_auto_20181013_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='no',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
