# Generated by Django 2.1.2 on 2018-10-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_remove_pic_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='i',
            field=models.ImageField(max_length=200, null=True, upload_to='media'),
        ),
    ]
