# Generated by Django 2.1.2 on 2018-10-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_auto_20181013_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='i',
            field=models.ImageField(default=32, max_length=200, upload_to='media'),
            preserve_default=False,
        ),
    ]
