# Generated by Django 2.1.2 on 2018-10-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0006_auto_20181013_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='i',
            field=models.ImageField(upload_to='media'),
        ),
    ]
